### ISSUE TITLE
队列可以用链表实现

### ISSUE THREAD

**Issue by 107nationalstation** [liyu4/learn-algorithm-365#1]
冲突的时候要复制大段内容...
跳表注释有bug的地方没问题，排序是按key排的...

**Comment by liyu4** [comment]
1: 谢谢你的提问，队列完全是可以用链表实现的，这里提供的只是一个简单的array版本。
2: 请问你说的冲突的地方指的hash table还是什么呢？
3: 恩，没有bug，这个注释我拿掉

另外： 如果用golang自带的list来实现队列是最简单的。

**Comment by 107nationalstation** [comment]
其实就是队列满了你扩充那段复制了...

**Comment by liyu4** [comment]
恩， 严格上来说这不算一个循环队列，稍后我会更新一个新的版本。谢谢你的意见。

**Comment by liyu4** [comment]
已更新
