### ISSUE TITLE
How to run the tests?

### ISSUE THREAD

**Issue by jutkko** [liyu4/learn-algorithm-365#3]
In the `datastructure` folder, I can't do `go test` to run the tests. Neither did `go test stack_test.go` work. :(

**Comment by jutkko** [comment]
```
± |master U:2 ✗| → go test stack_test.go
# command-line-arguments
./stack_test.go:8: undefined: New
FAIL    command-line-arguments [build failed]
 2017-02-26 22:08:30  ~/workspace/learn-algo/src/github.com/jutkko/learn-algorithm-365/datastructure
```

```
± |master U:2 ✗| → go test
# github.com/jutkko/learn-algorithm-365/datastructure
./queue.go:5: Node redeclared in this block
        previous declaration at ./doublylist.go:12
FAIL    github.com/jutkko/learn-algorithm-365/datastructure [build failed]
 2017-02-26 22:08:52  ~/workspace/learn-algo/src/github.com/jutkko/learn-algorithm-365/datastructure
```

**Comment by liyu4** [comment]
if you want to run test cases in a special file. In this example, it would be:
go test -v stack_test.go stack.go

I'd recommend to use the name pattern. Or, where/when possible, always run all package tests.

result:
# aliasliyu4 at alialliyu4.local in ~/svn/src/learn-algorithm-365/datastructure on git:master ✖︎ [9:52:22]
→ go test -v stack_test.go stack.go
=== RUN   TestStack
--- PASS: TestStack (0.00s)
	stack_test.go:11: stack is empty
	stack_test.go:19: 2000
	stack_test.go:22: &{[1]}
PASS
ok  	command-line-arguments	0.012s

**Comment by liyu4** [comment]
special --> specified

**Comment by liyu4** [comment]
@jutkko

**Comment by jutkko** [comment]
@liyu4 what about `go test`?

**Comment by liyu4** [comment]
Maybe you need to know this document  https://golang.org/pkg/testing/

**Comment by jutkko** [comment]
@liyu4 But it gives me an error.

**Comment by liyu4** [comment]
@jutkko No one error on my mac. Can you show your error code?

When I run this command in my terminal, I get this:

→ pwd
/Users/admin/svn/src/learn-algorithm-365/datastructure

# aliasliyu4 at alialliyu4.local in ~/svn/src/learn-algorithm-365/datastructure on git:master ✖︎ [13:00:22]
→ go test -v stack_test.go stack.go
=== RUN   TestStack
--- PASS: TestStack (0.00s)
PASS
ok  	command-line-arguments	0.006s

# aliasliyu4 at alialliyu4.local in ~/svn/src/learn-algorithm-365/datastructure on git:master ✖︎ [13:00:30]
→

That's ok!

**Comment by jutkko** [comment]
@liyu4 when I run `go test` I get

```
± |master U:2 ✗| → go test
# github.com/jutkko/learn-algorithm-365/datastructure
./queue.go:5: Node redeclared in this block
        previous declaration at ./doublylist.go:12
FAIL    github.com/jutkko/learn-algorithm-365/datastructure [build failed]
 2017-02-26 22:08:52  ~/workspace/learn-algo/src/github.com/jutkko/learn-algorithm-365/datastructure
```

**Comment by liyu4** [comment]
@jutkko
This command will run all test files! And I had know you want to expression! I will to fix it.

**Comment by liyu4** [comment]
@jutkko  please 'git pull' before you run 'go test' command.
